import asyncio
import os
import uuid

from fastapi import FastAPI

from gateway.app.models import ChatCompletionRequest


app = FastAPI(
    title="Mock Inference Backend",
    version="0.1.0",
)

BACKEND_NAME = os.getenv("BACKEND_NAME", "mock-vllm")


@app.get("/health")
async def health() -> dict[str, str]:
    return {
        "status": "healthy",
        "backend": BACKEND_NAME,
    }


@app.post("/v1/chat/completions")
async def create_chat_completion(
    request: ChatCompletionRequest,
) -> dict[str, object]:
    # Simulate inference latency.
    await asyncio.sleep(0.5)

    return {
        "id": f"chatcmpl-{uuid.uuid4()}",
        "object": "chat.completion",
        "model": request.model,
        "backend": BACKEND_NAME,
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": (f"Mock response generated by {BACKEND_NAME}."),
                },
                "finish_reason": "stop",
            }
        ],
    }
